apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: {{ .Release.Name }}
spec:
  credentials:
    - filename: terraform.tfvars.json
      secretRef:
        key: {{ .Values.crossplaneTerraformProvider.connectionSecretRef.key }}
        name: {{ .Values.crossplaneTerraformProvider.connectionSecretRef.name }}
        namespace: {{ .Values.crossplaneTerraformProvider.connectionSecretRef.namespace }}
      source: Secret
  configuration: |
    provider "dynatrace" {
      dt_env_url    = var.dt_env_url
      dt_api_token  = var.dt_api_token
    }

    variable "dt_env_url" {
      type = string
    }

    variable "dt_api_token" {
      type = string
    }

    terraform {
      required_providers {
        dynatrace = {
          version = "1.52.0"
          source = "dynatrace-oss/dynatrace"
        }
      }

      // Modules _must_ use remote state. The provider does not persist state.
      backend "kubernetes" {
        secret_suffix     = "{{ .Release.Name }}"
        namespace         = "crossplane-system"
        in_cluster_config = true
      }
    }