apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  name: {{ .Release.Name }}.log-event
  namespace: {{ .Release.Namespace }}
spec:
  forProvider:
    source: Inline
    module: |
      resource "dynatrace_log_events" "emergency_logs" {
        enabled = true
        query   = "dt.kubernetes.cluster.name == \"a-team-cluster\" and k8s.namespace.name == \"production\" and loglevel == \"EMERGENCY\""
        summary = "{{ .Values.workloadName }} ({{ .Values.cluster }}/{{ .Values.namespace }}) - Emergency Log"
        event_template {
          title       = "Emergency Logs found in {{ .Values.workloadName }} ({{ .Values.cluster }}/{{ .Values.namespace }})"
          description = "We have discovered logs with level 'EMERGENCY' in the workload {{ .Values.workloadName }} ({{ .Values.cluster }}/{{ .Values.namespace }}): {content}"
          event_type  = "CUSTOM_ALERT"
          davis_merge = true
        }
      }