apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-create-dashboards
  namespace: {{ .Release.Namespace }}
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: create-dashboards
    spec:
      volumes:
        - name: scripts
          configMap:
            name: {{ .Release.Name }}-scripts
            defaultMode: 0777
        - name: dashboards
          configMap:
            name: {{ .Release.Name }}-dashboards
            defaultMode: 0777
      containers:
        - name: create-dashboard
          image: alpine:latest
          volumeMounts:
            - mountPath: /scripts
              name: scripts
            - mountPath: /dashboards
              name: dashboards
          env:
            - name: OAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.oauthCredentialsSecretName }}
                  key: clientId
            - name: OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.oauthCredentialsSecretName }}
                  key: clientSecret
          command:
            - /bin/sh
            - -c
            - /scripts/create-dashboards.sh
      restartPolicy: Never
