apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-scripts
  namespace: {{ .Release.Namespace }}
data:
  create-dashboard.sh: |
    printf "Installing packages\n"
    apk add curl
    apk add jq

    printf "\nFetching OAuth token\n"
    token=$(curl --request POST 'https://sso-sprint.dynatracelabs.com/sso/oauth2/token' \
    --silent \
    --header 'Content-Type: application/x-www-form-urlencoded' \
    --data-urlencode 'grant_type=client_credentials' \
    --data-urlencode "client_id=$OAUTH_CLIENT_ID" \
    --data-urlencode "client_secret=$OAUTH_CLIENT_SECRET" \
    --data-urlencode 'scope=document:documents:write document:documents:read' \
    | jq -r .access_token)

    printf "\nCreating dashboard\n"
    {{- if .Values.dashboards.crossplaneMetrics.enabled }}
    documentId=$(curl --request POST 'https://ypd98635.sprint.apps.dynatracelabs.com/platform/document/v1/documents' \
    --silent \
    --header "Authorization: Bearer $token" \
    --header 'Content-Type: multipart/form-data' \
    --form name="Crossplane ({{ .Values.cluster }})" \
    --form type=dashboard \
    --form content=@dashboards/crossplaneMetrics.json \
    | jq -r .id)

    # TODO configure dashboard access
    {{- end }}